server:
  port: 8086

spring:
  application:
    name: locker-service

  datasource:
    url: jdbc:mysql://localhost:3306/locker_db?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: Pragyan4044@#1
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true

logging:
  level:
    com.banking.locker: DEBUG
